### ISSUE TITLE
Build fails due to sqlcipher3-wheels on MacOS Sonoma / Python 3.13

### ISSUE THREAD

**Issue by SokolskyNikita** [carderne/signal-export#144]
**Desktop (please complete the following information):**
- OS and version: macOS 14 (arm64)
- Terminal/shell used: zsh
- Python and pip version: Python 3.13, pip 24.2

**Describe the bug**
Installation of `signal-export` fails during the wheel build process for the `sqlcipher3-wheels` dependency. The error occurs during the compilation of C code, raising multiple deprecated function warnings and several undeclared function errors. This results in a failed attempt to build an installable wheel for `sqlcipher3-wheels`.

**To reproduce**
1. Run `python3 -m pip install signal-export` on macOS 14 (arm64) with Python 3.13.
2. Observe that the installation fails during the wheel build for `sqlcipher3-wheels`, throwing errors.

**Relevant log lines:**
```
src/connection.c:1157:18: error: call to undeclared function '_PyLong_AsInt'; 
ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

src/connection.c:1491:27: error: call to undeclared function '_PyObject_CallMethodIdObjArgs'; 

src/connection.c:1491:25: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]

src/connection.c:1498:17: error: call to undeclared function '_PyUnicode_EqualToASCIIString';

src/connection.c:1526:10: error: call to undeclared function '_PyArg_NoKeywords'; 

src/connection.c:1760:9: error: unknown type name '_PyTime_t'; did you mean 'PyTime_t'?

src/connection.c:1761:13: error: call to undeclared function '_PyTime_FromSecondsObject'; 

src/connection.c:1762:39: error: use of undeclared identifier '_PyTime_ROUND_CEILING'

src/connection.c:1765:24: error: call to undeclared function '_PyTime_AsMilliseconds'; 
```

**Comment by SokolskyNikita** [comment]
Ended up bypassing the problem by installing a prebuilt binary from https://pypi.org/project/sqlcipher3-wheels/#files

**Comment by carderne** [comment]
Haven't tested yet with Python 3.13, presumably [sqlcipher3-wheels](https://github.com/laggykiller/sqlcipher3) maintainer needs to make some small changes.

Be great if you can open an issue over at that repo!

**Comment by pro-sumer** [comment]
I'm also running into this :cry:

> Ended up bypassing the problem by installing a prebuilt binary from https://pypi.org/project/sqlcipher3-wheels/#files

Can you please post how you worked around the issue? (Which binary to download? Where to put it?)

**Comment by SokolskyNikita** [comment]
1. Go to https://pypi.org/project/sqlcipher3-wheels/#files
2. Download the latest binary for either arm64 or x86, depending on which Mac you have. In my case I downloaded `sqlcipher3_wheels-0.5.2.post1-cp312-cp312-macosx_11_0_arm64.whl`
3. Run `pip install sqlcipher3_wheels-0.5.2.post1-cp312-cp312-macosx_11_0_arm64.whl` to install it
4. Run `pip install signal-export`, which should now succeed

In my case `pip` is aliased to `python3 -m pip` to ensure I'm using python3 to install my packages.

**Comment by SokolskyNikita** [comment]
(Reopening for visibility, until sqlcipher is fixed in `pip install`

**Comment by pro-sumer** [comment]
I can install it if I rename `sqlcipher3_wheels-0.5.2.post1-cp312-cp312-macosx_11_0_arm64.wh` into `sqlcipher3_wheels-0.5.2.post1-cp313-cp313-macosx_12_0_arm64.wh` (my Python version is 3.13.0 and I use macOS Sequoia 15.0.1), but then it fails at runtime with this error:

```
ModuleNotFoundError: No module named 'sqlcipher3._sqlite3'
```

What am I doing wrong?

**Comment by SokolskyNikita** [comment]
> I can install it if I rename sqlcipher3_wheels-0.5.2.post1-cp312-cp312-macosx_11_0_arm64.wh into sqlcipher3_wheels-0.5.2.post1-cp313-cp313-macosx_12_0_arm64.wh

You can't just rename it, you have to actually downgrade to Python 3.12.

1. `brew install python@3.12`
2. `brew unlink python@3.13 && brew link python@3.12`
3. `alias python3='/opt/homebrew/bin/python3.12`
4. Run `pip install` for the downloaded binary, then install signal-export (see my previous comment)

**Comment by pro-sumer** [comment]
I was afraid of that... Thank you for this additional information!

**Comment by KRider92** [comment]
Bumping this as I have the same issue as @mazzacake - Tried the same steps as above, but get either
```
user@my-MacBook-Pro-m2Pro-2023 ~ % pipx install /Users/myUser/Library/CloudStorage/OneDrive-Personal/Downloads/sqlcipher3_wheels-0.5.2.post1-cp312-cp312-macosx_10_9_universal2.whl
ERROR: sqlcipher3_wheels-0.5.2.post1-cp312-cp312-macosx_10_9_universal2.whl is not a supported wheel on this platform.
Cannot determine package name from spec '/Users/myUser/Library/CloudStorage/OneDrive-Personal/Downloads/sqlcipher3_wheels
-0.5.2.post1-cp312-cp312-macosx_10_9_universal2.whl'. Check package spec for errors.
```
or
```
user@my-MacBook-Pro-m2Pro-2023 ~ % pip3 install /Users/myUser/Library/CloudStorage/OneDrive-Personal/Downloads/sqlcipher3_wheels-0.5.2.post1-cp312-cp312-macosx_10_9_universal2.whl 
Defaulting to user installation because normal site-packages is not writeable
ERROR: sqlcipher3_wheels-0.5.2.post1-cp312-cp312-macosx_10_9_universal2.whl is not a supported wheel on this platform.
WARNING: You are using pip version 21.2.4; however, version 24.3.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
```

Any help here would be **greatly appreciated**.

**Comment by carderne** [comment]
I've opened an issue with the sqlcipher3-wheels maintainer:
https://github.com/laggykiller/sqlcipher3/issues/3

If he doesn't resolve it in a little while I'll look at forking it, but would much prefer not to.

**Comment by laggykiller** [comment]
Released sqlcipher3-wheels v0.5.6, should be resolved now

**Comment by pro-sumer** [comment]
@laggykiller You mention 0.5.6 both here and in your own repository, but the latest available is 0.5.4?

https://pypi.org/project/sqlcipher3-wheels/#history

@carderne  Build still fails (maybe related to the above?):

```
Building wheels for collected packages: pysqlcipher3
  Building wheel for pysqlcipher3 (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pysqlcipher3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [114 lines of output]
...
      ValueError: No distribution was found. Ensure that `setup.py` is not empty and that it calls `setup()`.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pysqlcipher3
Failed to build pysqlcipher3
ERROR: Failed to build installable wheels for some pyproject.toml based projects (pysqlcipher3)
```

**Comment by laggykiller** [comment]
@pro-sumer my bad, should be v0.5.4, corrected

You are trying to install pysqlcipher3, not sqlcipher3-wheels. Check requirements.txt or pyproject.toml and try again

**Comment by yarko** [comment]
@laggykiller - looking at git@github.com:laggykiller/sqlcipher3.git:

- cloned & able to build
- used this wheel in a python 3.13.1 venv

@carderne:

- in current carderne/signal-export repo, `pip install -r requirements.lock` succeeded
- `sigexport -h` runs fine
- `sigexport -l` fails to find Signal source dir;
- `sigexport --source ~/.config/Signal/ -l` -- fails w/ KeyError: 'conversationId' in sigexport/data.py:78 in fetch_data

Going back to my python 3.12 venv,  I note that sigexport has not trouble finding Signal default source on Linux (on 3.13.1, it fails).

With the new wheel (assuming the current repository state on laggykiller/sqlcipher3.git) both python3.12 and 3.13.1 versions hung up on "KeyError: 'conversationId'.  embedding an ipython call just before the failure, and playing with what the issue is with `res.get("type")`  it seems now a "None" return from get("type") causes an issue, so I added that in the exclusion list (in signal-export > data.py, around line 75).

**Comment by laggykiller** [comment]
@yarko by lucky coincidence, new version of sqlcipher3-wheels and signal-export are released on the same day

The problem you mentioned is a bug in new version of signal-export, not due to new version of sqlcipher3-wheels, right?

**Comment by yarko** [comment]
@laggykiller Possibly, but looking at a repo diff a few different commits back, nothing stands out as anything affecting this...  so not sure.  Might (?) also be about a new Signal release in the last few days?

**Comment by laggykiller** [comment]
@yarko does it fails if:

A. Install sqlcipher3-wheels 0.5.2.post1 with latest version of signal-export on python3.12
B. Install sqlcipher3-wheels 0.5.4 with last good version of signal-export on python3.12

**Comment by yarko** [comment]
> [@yarko](https://github.com/yarko) does it fails if:

Referring to the data.py KeyError:
> 
> A. Install sqlcipher3-wheels 0.5.2.post1 with latest version of signal-export on python3.12

Did not try this combination of latest version of signal-export;  the version of sigexport installed in python3.12 which worked was installed Feb. 1 2025.

> B. Install sqlcipher3-wheels 0.5.4 with last good version of signal-export on python3.12

This failed with the latest version of sigexport in both python3.12 and python3.13.1 - however:  python 3.13.1 failed to work with any attempts before trying the most recent import of sqpcipher3, wheels built from clone and local build.

This is on:

Operating System: Ubuntu 22.04.5 LTS              
          Kernel: Linux 6.8.0-52-generic
    Architecture: x86-64
 Hardware Vendor: Framework
  Hardware Model: Laptop 13 _AMD Ryzen 7040Series_

Python 3.13.1 built locally from source tree.

**Comment by yarko** [comment]
Footnote:
I do not have `rye` installed. The way I tested this
was in one directory, with two venv’s, alternately activated.

Installing sigexport resulted in referencing the code in the cloned repository, rather than installing the code into the venv, which means that the 3.12 tests were affected by 3.13 intended debugging and changes - an unfortunate situation.

**Comment by pro-sumer** [comment]
> You are trying to install pysqlcipher3, not sqlcipher3-wheels. Check requirements of pyproject.toml and try again

Oops. That's a leftover from experiments when this was broken... 🤦

Will try again tonight with a clean install.

**Comment by pro-sumer** [comment]
Works indeed 🎉

Thank you!
