### ISSUE TITLE
Docker process failed - Command '['docker', 'run', '--rm', '--volume=Signal:/Signal', 'carderne/sigexport:latest']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by noahjgente** [carderne/signal-export#84]
**Setup:**
I am on Lubuntu 20.04 and have installed Signal as a snap in version 5.63.0. I installed signal-export through docker in version 1.2.2. 

**What I did**
I ran the export using

`sigexport --source ./Signal /path-for-export`

It fails with the following output:

```
Using Docker to extract data, this may take a while the first time!                                                               
Docker process failed, see logs below:
Command '['docker', 'run', '--rm', '--volume=Signal:/Signal', 'carderne/sigexport:latest']' returned non-zero exit status 1.
```
When I tried the same thing yesterday, I did not get this error. 
I do not see any more information here - let me know if there is a way to get more detailed logs here

**Comment by carderne** [comment]
Should be fixed now by https://github.com/carderne/signal-export/commit/a592429c369e385d26d1caeb5e2637b31882bf10
(Let me know (and re-open this issue) if not.)
Thanks for that!

**Comment by noahjgente** [comment]
@carderne thanks for your quick reply! Unfortunately the problem persists. I do not have the privilege to reopen the issue, though.

**Comment by carderne** [comment]
Sorry forgot to bump version.
If you `pip install --upgrade signal-export` that should resolve it!

**Comment by noahjgente** [comment]
Now it works, thanks a lot!
